export const CHANGE_STATUS_LIST_FOR_SALE = "CHANGE_STATUS_LIST_FOR_SALE";
export const CHANGE_STATUS_DELIST_FOR_SALE = "CHANGE_STATUS_DELIST_FOR_SALE";
export const CHANGE_STATUS_MAKE_OFFER = "CHANGE_STATUS_MAKE_OFFER";
export const CHANGE_STATUS_CANCEL_OFFER = "CHANGE_STATUS_CANCEL_OFFER";
export const CHANGE_STATUS_ACCEPT_OFFER = "CHANGE_STATUS_ACCEPT_OFFER";
