export const CREATE_PROVIDER = "CREATE_PROVIDER";
export const UPDATE_PROVIDER = "UPDATE_PROVIDER";
export const DELETE_PROVIDER = "DELETE_PROVIDER";
export const SET_WALLET_ADDRESS = "SET_WALLET_ADDRESS";
export const SET_USER_LISTED_INFO = "SET_USER_LISTED_INFO";